swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /login:
    post:
      operationId: Login
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /logout:
    post:
      operationId: Logout
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /register:
    post:
      operationId: Register
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
