swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /account/info:
    post:
      operationId: Info
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /apply:
    post:
      operationId: Apply
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /card-type/list:
    post:
      operationId: List
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /login:
    post:
      operationId: Login
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /logout:
    post:
      operationId: Logout
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /register:
    post:
      operationId: Register
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /user/list:
    post:
      operationId: List
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
